# Generated by Django 3.2 on 2024-08-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20240819_1702'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_username_email',
        ),
    ]
